const endpoints = {
    gg: process.env.GOOGLE_API_KEY,
    baseUrl: process.env.NODE_ENV === 'development' ? process.env.BASE_URL_DEV : process.env.BASE_URL,
    socketUrl: process.env.NODE_ENV === 'development' ? process.env.SOCKET_URL_DEV : process.env.SOCKET_URL,
    login: '/dispatch/login',
    signUp: '/dispatch/signup',
    forgotPassword: '/dispatch/forgot/password',
    resetPassword: '/dispatch/reset/password',
    verify: '/dispatch/confirm/email',
    retriveProfile: '/dispatch/profile',
    updateProfile: '/dispatch/update/profile',
    updateVehicle: '/dispatch/update/vehicle',
    uploadPhoto: '/dispatch/update/photo',
    updateStatus: '/dispatch/update/status',
    listOdrders: '/dispatch/list/order',
    acceptOrders: '/dispatch/accept/order',
    myOrders: '/dispatch/myorder',
    verifyOrder: '/dispatch/pickup/order',
    city: '/dispatch/order/city',
    startDispatch: '/dispatch/start/dispatch',
    deliverOrder: '/dispatch/delivered/order',
    history: '/dispatch/order/history',
    cancelOrder: '/dispatch/cancel/order',
    fundwallet: '/dispatch/fund/wallet',
    getBalance: '/dispatch/wallet/balance',
    walletHistory: '/dispatch/fund/history',
    chat: '/dispatch/chat/support',
    getBanks: '/dispatch/retrieve/bank',
    verifyBank: '/dispatch/confirm/account',
    withdraw: '/dispatch/withdraw/fund',

    //business
    addRider: '/bussiness/add/dispatch',
    retriveFleets: '/bussiness/retrieve/all/fleet',
    singleFleet: '/bussiness/retrieve/single/fleet',
    deliveryHistory: '/bussiness/delivery/history',
    allOrders: '/bussiness/retrieve/all/order',
    dashboard: '/bussiness/dashboard',
    fleetOrders: '/bussiness/retrieve/fleet/order',
    fleetDetails: '/bussiness/retrieve/single/fleet',
    updateFleet: '/bussiness/update/dispatch',
    activeFleet: '/bussiness/active/rider',
    blockFleet: '/bussiness/block/fleet',
    unblockFleet: '/bussiness/unblock/fleet'
}

export default endpoints;